import Head from "next/head";
import { Box, ThemeProvider } from "@mui/material";
import theme from "../styles/theme";

export default function Home() {
  return (
    <>
      <Head>
        <title>Toys market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Box>
          <p>Hello world!</p>
        </Box>
      </ThemeProvider>
    </>
  );
}
